services:
  transport-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50054:50054"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    external: true